services:
  postgres:
    restart: always
    image: postgres:13
    environment:
      - POSTGRES_DB=pruebatecnica
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin1234
    ports:
      - 5433:5432
    networks:
      - my_network

networks:
  my_network:
    driver: bridge